In [209]:
import dotenv
import os
from sqlalchemy import create_engine
import pandas as pd
dotenv.load_dotenv(dotenv_path=".env", override=True)
username = os.getenv("username")
password = os.getenv("password")
host = os.getenv("host")
dbname = os.getenv("dbname")
conn_string = "mysql+pymysql://" + username + ":" + password + "@" + host + "/" + dbname
db_engine = create_engine(conn_string)
query= "SELECT * FROM dimproduct"
df=pd.read_sql(query,db_engine)

In [7]:
#dati totali
Totale=df.size
print("il numero di dati totali nel DataSet è:",Totale)

il numero di dati totali nel DataSet è: 21816

In [15]:
#metadati
print("L'elenco dei metadati è",df.columns)

L'elenco dei metadati è Index(['ProductKey', 'ProductAlternateKey', 'ProductSubcategoryKey',
       'WeightUnitMeasureCode', 'SizeUnitMeasureCode', 'EnglishProductName',
       'SpanishProductName', 'FrenchProductName', 'StandardCost',
       'FinishedGoodsFlag', 'Color', 'SafetyStockLevel', 'ReorderPoint',
       'ListPrice', 'Size', 'SizeRange', 'Weight', 'DaysToManufacture',
       'ProductLine', 'DealerPrice', 'Class', 'Style', 'ModelName',
       'LargePhoto', 'EnglishDescription', 'FrenchDescription',
       'ChineseDescription', 'ArabicDescription', 'HebrewDescription',
       'ThaiDescription', 'GermanDescription', 'JapaneseDescription',
       'TurkishDescription', 'StartDate', 'EndDate', 'Status'],
      dtype='object')

In [19]:
#prima riga
df.head(1)

,ProductKey,ProductAlternateKey,ProductSubcategoryKey,WeightUnitMeasureCode,SizeUnitMeasureCode,EnglishProductName,SpanishProductName,FrenchProductName,StandardCost,FinishedGoodsFlag,...,ChineseDescription,ArabicDescription,HebrewDescription,ThaiDescription,GermanDescription,JapaneseDescription,TurkishDescription,StartDate,EndDate,Status
0,1,AR-5381,NaN,None,None,Adjustable Race,,,NaN,0,...,None,None,None,None,None,None,None,2003-07-01,NaT,Current

In [21]:
#ultima riga
df.tail(1)

,ProductKey,ProductAlternateKey,ProductSubcategoryKey,WeightUnitMeasureCode,SizeUnitMeasureCode,EnglishProductName,SpanishProductName,FrenchProductName,StandardCost,FinishedGoodsFlag,...,ChineseDescription,ArabicDescription,HebrewDescription,ThaiDescription,GermanDescription,JapaneseDescription,TurkishDescription,StartDate,EndDate,Status
605,606,BK-R19B-52,2.0,LB,CM,"Road-750 Black, 52","Carretera: 750, negra, 52","Vélo de route 750 noir, 52",343.65,1,...,入门级成人自行车；确保越野旅行或公路骑乘的舒适。快拆式车毂和轮缘。,إنها دراجة مناسبة للمبتدئين من البالغين؛ فهي ت...,"אופני מבוגרים למתחילים; מציעים רכיבה נוחה ""מחו...",จักรยานระดับเริ่มต้นสำหรับผู้ใหญ่ ให้ความสบายใ...,Ein Erwachsenenrad für Einsteiger; bietet Komf...,エントリー レベルに対応する、クロスカントリーにも街への買い物にも快適な、大人の自転車。ハブ...,"""Başlangıç seviyesinde yetişkin bisikleti, kır...",2013-07-01,NaT,Current

In [23]:
df.sample(5)

,ProductKey,ProductAlternateKey,ProductSubcategoryKey,WeightUnitMeasureCode,SizeUnitMeasureCode,EnglishProductName,SpanishProductName,FrenchProductName,StandardCost,FinishedGoodsFlag,...,ChineseDescription,ArabicDescription,HebrewDescription,ThaiDescription,GermanDescription,JapaneseDescription,TurkishDescription,StartDate,EndDate,Status
573,574,BK-T79U-50,3.0,LB,CM,"Touring-1000 Blue, 50","Paseo: 1000, azul, 50","Vélo de randonnée 1000 bleu, 50",1481.94,1,...,享受时尚舒适的旅行。专门设计，最大程度地确保舒适和安全。速度可调，轻松翻越所有类型的山坡。采...,الاستمتاع بالمظهر الأنيق والراحة عند السفر. لق...,רכיבה מסוגננת ונוחה. עיצוב המיועד למרב הנוחות ...,เดินทางอย่างมาดมั่นและสะดวกสบาย ได้รับการออกแ...,Fahren Sie mit Stil und Komfort. Design für ma...,スタイルと乗り心地を同時に実現。最大限の快適性と安全性を目標に設計され、ワイドなギア レンジ...,"""Tarz ve konforlu yolculuk. Maksimum konfor ve...",2013-07-01,NaT,Current
40,41,HJ-1428,NaN,None,None,Thin-Jam Hex Nut 2,,,NaN,0,...,None,None,None,None,None,None,None,2003-07-01,NaT,Current
437,438,FR-R92B-62,14.0,LB,CM,"HL Road Frame - Black, 62","Cuadro de carretera GA: negro, 62","Cadre de vélo de route HL - noir, 62",868.63,1,...,重量最轻、质量最好的铝制车架采用最新的合金材质；经过焊接和热处理，坚固牢靠。我们创新的设计确...,لقد تم صناعة هيكل دراجتنا الألومنيوم الأخف وزن...,מסגרת האלומיניום הקלה והאיכותית ביותר שלנו עשו...,เฟรมอลูมิเนียมคุณภาพสูงสุดและน้ำหนักเบาที่สุด ...,Unser leichtester und hochwertigster Aluminium...,最新の合金で作られた最軽量/最高品質のアルミニウム フレームで、強度を得るために溶接および熱...,"""En yeni alaşımdan imal edilme, en hafif ve en...",2013-07-01,NaT,Current
108,109,LJ-5161,NaN,None,None,Thin-Jam Lock Nut 3,,,NaN,0,...,None,None,None,None,None,None,None,2003-07-01,NaT,Current
62,63,HN-3816,NaN,None,None,Hex Nut 12,,,NaN,0,...,None,None,None,None,None,None,None,2003-07-01,NaT,Current

In [28]:
df["Color"].unique()

array(['NA', 'Black', 'Silver', 'Red', 'White', 'Blue', 'Multi', 'Yellow',
       'Grey', 'Silver/Black'], dtype=object)

In [48]:
Pesante=df["Weight"].max()
print(Pesante)

1050.0

In [46]:
Leggero=df["Weight"].min()
print(Leggero)

2.12

In [50]:
Media=df["DealerPrice"].mean()
print(Media)

448.5970597468353

In [183]:
filtro=(df["Weight"]<100000)
prodotti=df.loc[filtro,"ProductKey"]
prodotti_unici=prodotti.unique()
numero_prodotti=len(prodotti_unici)
print(numero_prodotti)

282

In [147]:
prodotti_ordinati=df.sort_values(by="StandardCost", ascending=True)
numero_quarto=int(len(prodotti_ordinati)/4-1)
primo_quarto=prodotti_ordinati.iloc[0:numero_quarto]
max_quarto=primo_quarto["StandardCost"].max()
min_quarto=primo_quarto["StandardCost"].min()
print(min_quarto,max_quarto)

0.86 144.59

In [106]:
filtro=df["Color"]=="Blue"
prodotti_blue=df.loc[filtro]
prezzomedio=prodotti_blue["StandardCost"].mean()
print(prezzomedio)

527.5721428571429

In [118]:
df[["StandardCost","DealerPrice"]].tail(20)

     StandardCost  DealerPrice
586        419.78      461.694
587        419.78      461.694
588        419.78      461.694
589        419.78      461.694
590        308.22      338.994
591        308.22      338.994
592        308.22      338.994
593        308.22      338.994
594        308.22      338.994
595        294.58      323.994
596        294.58      323.994
597        294.58      323.994
598        294.58      323.994
599        294.58      323.994
600         23.97       32.394
601         44.95       60.744
602         53.94       72.894
603        343.65      323.994
604        343.65      323.994
605        343.65      323.994

In [135]:
filtro1=df["Color"].isin(["Black","Red"])
filtro2=(df["Color"]=="Black") | (df["Color"]=="Red")
prezzo_medio1=df.loc[filtro1,"StandardCost"].mean()
prezzo_medio2=df.loc[filtro2,"StandardCost"].mean()
print(prezzo_medio1)
print(prezzo_medio2)

537.4548437500001
537.4548437500001

In [213]:
filtro=(df["Size"]=="42") & (df["Weight"]>10)
prodotti_filtrati=df.loc[filtro]
max_price=prodotti_filtrati["DealerPrice"].max()
print(max_price)

2039.994

In [151]:
df=pd.read_csv(r"C:\Users\pagod\OneDrive\Desktop\Python\beginner_datasets\amazon.csv")

In [153]:
df.shape

(20000, 2)

In [155]:
df.sample(10)

                                              reviewText  Positive
3224   It really helps me keep track of my spending a...         1
17732  I hate puzzles...the little cardboard jigsaws ...         1
4249   This game is way to hard and it is boring afte...         0
18542  This game is a rip-off!!!!! All you do is pres...         0
17724  this is an awesome puzzle game. if you like pu...         1
19699  Great game! It works great on my Kindle Fire. ...         1
2804   this is an amazing app!  I bought it almost a ...         1
11134  This app does what it says. I use it with Pand...         1
580    You and your kids will love this game! Throwin...         1
13872  I was connected to my web folder within 3 minu...         1

In [157]:
df.columns

Index(['reviewText', 'Positive'], dtype='object')

In [167]:
positive1=df["Positive"]==1
negative0=df["Positive"]==0
positive=df.loc[positive1]
negative=df.loc[negative0]
numero_p=positive.count()
numero_n=negative.count()
rapporto=numero_p/numero_n
print("il numero di recensioni postitive è ",numero_p," il unmero di recensioni negative è ",numero_n," e il loro rapporto è ",rapporto)

il numero di recensioni postitive è  reviewText    15233
Positive      15233
dtype: int64  il unmero di recensioni negative è  reviewText    4767
Positive      4767
dtype: int64  e il loro rapporto è  reviewText    3.195511
Positive      3.195511
dtype: float64

In [165]:
df["Positive"].value_counts()

Positive
1    15233
0     4767
Name: count, dtype: int64

In [185]:
df=pd.read_csv(r"C:\Users\pagod\OneDrive\Desktop\Python\beginner_datasets\diabetes.csv")
print(df.shape)
df.head(5)

(768, 9)

,Number of times pregnant,Plasma glucose concentration a 2 hours in an oral glucose tolerance test,Diastolic blood pressure (mm Hg),Triceps skin fold thickness (mm),2-Hour serum insulin (mu U/ml),Body mass index (weight in kg/(height in m)^2),Diabetes pedigree function,Age (years),Class variable
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [173]:
df.columns

Index(['Number of times pregnant',
       'Plasma glucose concentration a 2 hours in an oral glucose tolerance test',
       'Diastolic blood pressure (mm Hg)', 'Triceps skin fold thickness (mm)',
       '2-Hour serum insulin (mu U/ml)',
       'Body mass index (weight in kg/(height in m)^2)',
       'Diabetes pedigree function', 'Age (years)', 'Class variable'],
      dtype='object')

In [175]:
df.describe()

,Number of times pregnant,Plasma glucose concentration a 2 hours in an oral glucose tolerance test,Diastolic blood pressure (mm Hg),Triceps skin fold thickness (mm),2-Hour serum insulin (mu U/ml),Body mass index (weight in kg/(height in m)^2),Diabetes pedigree function,Age (years),Class variable
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [199]:
filtro1=(df["Age (years)"]<20)
filtro2=(df["Age (years)"]>= 20) & (df["Age (years)"]<30)
filtro3=(df["Age (years)"]>=30) & (df["Age (years)"]<40)
filtro4=(df["Age (years)"]>=40) & (df["Age (years)"]<50)
filtro5=(df["Age (years)"]>50)
tab1=df.loc[filtro1]
tab2=df.loc[filtro2]
tab3=df.loc[filtro3]
tab4=df.loc[filtro4]
tab5=df.loc[filtro5]
media1=tab1["Diastolic blood pressure (mm Hg)"].mean()
media2=tab2["Diastolic blood pressure (mm Hg)"].mean()
media3=tab3["Diastolic blood pressure (mm Hg)"].mean()
media4=tab4["Diastolic blood pressure (mm Hg)"].mean()
media5=tab5["Diastolic blood pressure (mm Hg)"].mean()

print("La media per la prima fascia di età è:",media1)
print("La media per la seconda fascia di età è:",media2)
print("La media per la terza fascia di età è:",media3)
print("La media per la quarta fascia di età è:",media4)
print("La media per la quinta fascia di età è:",media5)

La media per la prima fascia di età è: nan
La media per la seconda fascia di età è: 65.34848484848484
La media per la terza fascia di età è: 69.66666666666667
La media per la quarta fascia di età è: 73.94067796610169
La media per la quinta fascia di età è: 78.38271604938272

In [215]:
df=pd.read_csv(r"C:\Users\pagod\OneDrive\Desktop\Python\beginner_datasets\insurance.csv")

In [205]:
print(df.shape)
print(df.head(10))
print(df.columns)

(1338, 7)
   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520
5   31  female  25.740         0     no  southeast   3756.62160
6   46  female  33.440         1     no  southeast   8240.58960
7   37  female  27.740         3     no  northwest   7281.50560
8   37    male  29.830         2     no  northeast   6406.41070
9   60  female  25.840         0     no  northwest  28923.13692
Index(['age', 'sex', 'bmi', 'children', 'smoker', 'region', 'charges'], dtype='object')

In [207]:
media_region=df.groupby("region")["charges"].mean()
print(media_region)

region
northeast    13406.384516
northwest    12417.575374
southeast    14735.411438
southwest    12346.937377
Name: charges, dtype: float64

In [225]:
df["smoker"].value_counts()
filtro1=df["smoker"]=="yes"
filtro2=df["smoker"]=="no"
tab_fumatori=df.loc[filtro1]
tab_non_fumatori=df.loc[filtro2]
media_fumatori=tab_fumatori.groupby("smoker")["charges"].mean()
media_non_fumatori=tab_non_fumatori.groupby("smoker")["charges"].mean()
print("La media di spesa per i fumatori è:",media_fumatori)
print("La medi di spesa per i non fumatori è:",media_non_fumatori)

La media di spesa per i fumatori è: smoker
yes    32050.231832
Name: charges, dtype: float64
La medi di spesa per i non fumatori è: smoker
no    8434.268298
Name: charges, dtype: float64

In [233]:
df["bmi"].describe()

count    1338.000000
mean       30.663397
std         6.098187
min        15.960000
25%        26.296250
50%        30.400000
75%        34.693750
max        53.130000
Name: bmi, dtype: float64

In [246]:
valori_media=[]
vettore=df["bmi"].unique()
for valore in vettore:
    filtro=(df["bmi"]==valore)
    tab=df.loc[filtro]
    media=tab["charges"].mean()
    print(f"il valore medio per il percentile{valore} è: {media}")

il valore medio per il percentile27.9 è: 16884.924
il valore medio per il percentile33.77 è: 1700.0923
il valore medio per il percentile33.0 è: 6853.870486666667
il valore medio per il percentile22.705 è: 12047.779170000002
il valore medio per il percentile28.88 è: 8271.059949999999
il valore medio per il percentile25.74 è: 7666.50485
il valore medio per il percentile33.44 è: 8865.145349999999
il valore medio per il percentile27.74 è: 13540.359933333333
il valore medio per il percentile29.83 è: 14239.110866666664
il valore medio per il percentile25.84 è: 14117.803264000002
il valore medio per il percentile26.22 è: 8398.75705
il valore medio per il percentile26.29 è: 27808.7251
il valore medio per il percentile34.4 è: 11952.101
il valore medio per il percentile39.82 è: 5840.112133333333
il valore medio per il percentile42.13 è: 24162.47495
il valore medio per il percentile24.6 è: 7954.34
il valore medio per il percentile30.78 è: 21516.8756
il valore medio per il percentile23.845 è: 10407.27355
il valore medio per il percentile40.3 è: 10602.385
il valore medio per il percentile35.3 è: 22871.591499999995
il valore medio per il percentile36.005 è: 13228.84695
il valore medio per il percentile32.4 è: 4149.736
il valore medio per il percentile34.1 è: 12245.810147499998
il valore medio per il percentile31.92 è: 16625.842
il valore medio per il percentile28.025 è: 14167.978149999999
il valore medio per il percentile27.72 è: 7278.38755
il valore medio per il percentile23.085 è: 8078.267650000001
il valore medio per il percentile32.775 è: 18435.786249999997
il valore medio per il percentile17.385 è: 2775.19215
il valore medio per il percentile36.3 è: 27132.404
il valore medio per il percentile35.6 è: 35585.576
il valore medio per il percentile26.315 è: 5608.469650000001
il valore medio per il percentile28.6 è: 8152.682333333333
il valore medio per il percentile28.31 è: 15961.313253333334
il valore medio per il percentile36.4 è: 51194.55914
il valore medio per il percentile20.425 è: 1625.43375
il valore medio per il percentile32.965 è: 12326.7101
il valore medio per il percentile20.8 è: 2755.5435
il valore medio per il percentile36.67 è: 29400.7394775
il valore medio per il percentile39.9 è: 48173.361
il valore medio per il percentile26.6 è: 10825.844333333334
il valore medio per il percentile36.63 è: 19433.6967
il valore medio per il percentile21.78 è: 9078.26289
il valore medio per il percentile30.8 è: 16077.000124999999
il valore medio per il percentile37.05 è: 19866.828833333333
il valore medio per il percentile37.3 è: 20630.28351
il valore medio per il percentile38.665 è: 3393.35635
il valore medio per il percentile34.77 è: 6289.940299999999
il valore medio per il percentile24.53 è: 12629.8967
il valore medio per il percentile35.2 è: 16952.47428571429
il valore medio per il percentile35.625 è: 13236.93475
il valore medio per il percentile33.63 è: 20834.558763333334
il valore medio per il percentile28.0 è: 14615.347150000001
il valore medio per il percentile34.43 è: 13764.6442
il valore medio per il percentile28.69 è: 13023.3701
il valore medio per il percentile36.955 è: 26120.0507
il valore medio per il percentile31.825 è: 17067.10375
il valore medio per il percentile31.68 è: 34487.6572
il valore medio per il percentile22.88 è: 23244.7902
il valore medio per il percentile37.335 è: 5328.5656500000005
il valore medio per il percentile27.36 è: 12882.235808571428
il valore medio per il percentile33.66 è: 7250.0332
il valore medio per il percentile24.7 è: 16527.187542500003
il valore medio per il percentile25.935 è: 6512.983983333333
il valore medio per il percentile22.42 è: 17149.658460000002
il valore medio per il percentile28.9 è: 7383.5666
il valore medio per il percentile39.1 è: 14235.072
il valore medio per il percentile36.19 è: 22270.296910000005
il valore medio per il percentile23.98 è: 16022.227169999998
il valore medio per il percentile24.75 è: 16577.7795
il valore medio per il percentile28.5 è: 13101.531696
il valore medio per il percentile28.1 è: 11353.586000000001
il valore medio per il percentile32.01 è: 6964.103899999999
il valore medio per il percentile27.4 è: 7111.870000000001
il valore medio per il percentile34.01 è: 11356.6609
il valore medio per il percentile29.59 è: 4255.1276
il valore medio per il percentile35.53 è: 23457.148765
il valore medio per il percentile39.805 è: 5101.71245
il valore medio per il percentile26.885 è: 15203.584149999999
il valore medio per il percentile38.285 è: 7935.29115
il valore medio per il percentile37.62 è: 20466.023800000003
il valore medio per il percentile41.23 è: 8821.8857
il valore medio per il percentile34.8 è: 18623.628004285714
il valore medio per il percentile22.895 è: 19256.5536675
il valore medio per il percentile31.16 è: 17853.387400000003
il valore medio per il percentile27.2 è: 6969.6335
il valore medio per il percentile26.98 è: 14822.713533333334
il valore medio per il percentile39.49 è: 2794.562433333333
il valore medio per il percentile24.795 è: 15578.6538
il valore medio per il percentile31.3 è: 47291.055
il valore medio per il percentile38.28 è: 8663.714383333334
il valore medio per il percentile19.95 è: 9049.190833333334
il valore medio per il percentile19.3 è: 15820.699
il valore medio per il percentile31.6 è: 8718.327666666666
il valore medio per il percentile25.46 è: 10315.94786142857
il valore medio per il percentile30.115 è: 10539.915491666667
il valore medio per il percentile29.92 è: 10357.029966666667
il valore medio per il percentile27.5 è: 10998.578855
il valore medio per il percentile28.4 è: 2087.019
il valore medio per il percentile30.875 è: 12611.780613750001
il valore medio per il percentile27.94 è: 11176.374266666666
il valore medio per il percentile35.09 è: 47055.5321
il valore medio per il percentile29.7 è: 11386.0136
il valore medio per il percentile35.72 è: 10774.655159999998
il valore medio per il percentile32.205 è: 10161.79095
il valore medio per il percentile28.595 è: 11276.566135
il valore medio per il percentile49.06 è: 11381.3254
il valore medio per il percentile27.17 è: 10412.1138
il valore medio per il percentile23.37 è: 11634.487299999999
il valore medio per il percentile37.1 è: 7507.946999999999
il valore medio per il percentile23.75 è: 5504.1331666666665
il valore medio per il percentile28.975 è: 9243.83585
il valore medio per il percentile31.35 è: 17971.50344625
il valore medio per il percentile33.915 è: 9104.427099999999
il valore medio per il percentile28.785 è: 8805.00035
il valore medio per il percentile28.3 è: 19081.620000000003
il valore medio per il percentile37.4 è: 14803.632133333333
il valore medio per il percentile17.765 è: 32734.1863
il valore medio per il percentile34.7 è: 21239.9905
il valore medio per il percentile26.505 è: 12815.44495
il valore medio per il percentile22.04 è: 13616.3586
il valore medio per il percentile35.9 è: 11163.568
il valore medio per il percentile25.555 è: 8050.330783333334
il valore medio per il percentile28.05 è: 5719.657166666667
il valore medio per il percentile25.175 è: 7296.785916666667
il valore medio per il percentile31.9 è: 16601.49562
il valore medio per il percentile36.0 è: 5361.8195
il valore medio per il percentile32.49 è: 20194.641089999997
il valore medio per il percentile25.3 è: 14039.723000000002
il valore medio per il percentile29.735 è: 14098.278530000001
il valore medio per il percentile38.83 è: 12360.924773333332
il valore medio per il percentile30.495 è: 16754.22305
il valore medio per il percentile37.73 è: 7637.6122
il valore medio per il percentile37.43 è: 6175.4977
il valore medio per il percentile24.13 è: 12215.7762
il valore medio per il percentile37.145 è: 6334.34355
il valore medio per il percentile39.52 è: 6948.7008
il valore medio per il percentile24.42 è: 22237.116456666667
il valore medio per il percentile27.83 è: 16332.96237
il valore medio per il percentile36.85 è: 12265.474900000001
il valore medio per il percentile39.6 è: 10543.891666666666
il valore medio per il percentile29.8 è: 13156.673162500001
il valore medio per il percentile29.64 è: 14386.20393
il valore medio per il percentile28.215 è: 12436.8721
il valore medio per il percentile37.0 è: 6814.611500000001
il valore medio per il percentile33.155 è: 5714.582649999999
il valore medio per il percentile18.905 è: 4827.90495
il valore medio per il percentile41.47 è: 11295.635633333331
il valore medio per il percentile30.3 è: 5003.472000000001
il valore medio per il percentile15.96 è: 1694.7964
il valore medio per il percentile33.345 è: 12376.389116
il valore medio per il percentile37.7 è: 48824.45
il valore medio per il percentile27.835 è: 7940.099050000002
il valore medio per il percentile29.2 è: 10436.096
il valore medio per il percentile26.41 è: 11236.7139
il valore medio per il percentile30.69 è: 6854.1291
il valore medio per il percentile41.895 è: 43753.33705
il valore medio per il percentile30.9 è: 17857.763666666666
il valore medio per il percentile32.2 è: 20319.075666666668
il valore medio per il percentile32.11 è: 9170.595891428571
il valore medio per il percentile31.57 è: 8697.593799999999
il valore medio per il percentile26.2 è: 4883.866
il valore medio per il percentile30.59 è: 8082.722375714286
il valore medio per il percentile32.8 è: 24199.63625333333
il valore medio per il percentile18.05 è: 9644.2525
il valore medio per il percentile39.33 è: 14901.5167
il valore medio per il percentile32.23 è: 13544.656545000002
il valore medio per il percentile24.035 è: 10679.86965
il valore medio per il percentile36.08 è: 24372.418450000005
il valore medio per il percentile22.3 è: 4625.0925
il valore medio per il percentile26.4 è: 14968.285510000002
il valore medio per il percentile31.8 è: 13880.949
il valore medio per il percentile26.73 è: 3309.2747
il valore medio per il percentile23.1 è: 2483.736
il valore medio per il percentile23.21 è: 10699.798088
il valore medio per il percentile33.7 è: 7919.244
il valore medio per il percentile33.25 è: 8627.499833333333
il valore medio per il percentile24.64 è: 19515.5416
il valore medio per il percentile33.88 è: 23453.021416666666
il valore medio per il percentile38.06 è: 25542.834324285715
il valore medio per il percentile41.91 è: 12386.080680000001
il valore medio per il percentile31.635 è: 8266.15565
il valore medio per il percentile36.195 è: 7443.64305
il valore medio per il percentile17.8 è: 1727.785
il valore medio per il percentile24.51 è: 3938.4665666666665
il valore medio per il percentile22.22 è: 19444.2658
il valore medio per il percentile38.39 è: 28943.822766666668
il valore medio per il percentile29.07 è: 23247.0203
il valore medio per il percentile22.135 è: 5867.66915
il valore medio per il percentile26.8 è: 19533.130785
il valore medio per il percentile30.02 è: 19102.076227499998
il valore medio per il percentile35.86 è: 15636.74265
il valore medio per il percentile20.9 è: 11513.956
il valore medio per il percentile17.29 è: 7813.353433333334
il valore medio per il percentile34.21 è: 14932.727900000002
il valore medio per il percentile25.365 è: 16950.000213333333
il valore medio per il percentile40.15 è: 17110.462499999998
il valore medio per il percentile24.415 è: 11520.09985
il valore medio per il percentile25.2 è: 11837.16
il valore medio per il percentile26.84 è: 9375.1336
il valore medio per il percentile24.32 è: 14055.981457142856
il valore medio per il percentile42.35 è: 46151.1245
il valore medio per il percentile19.8 è: 7266.665666666667
il valore medio per il percentile32.395 è: 12150.923522000001
il valore medio per il percentile30.2 è: 17976.366333333335
il valore medio per il percentile29.37 è: 5133.5638
il valore medio per il percentile34.2 è: 20605.2982
il valore medio per il percentile27.455 è: 7439.56595
il valore medio per il percentile27.55 è: 9106.168249999999
il valore medio per il percentile20.615 è: 2803.69785
il valore medio per il percentile24.3 è: 4052.4966666666674
il valore medio per il percentile31.79 è: 19432.087167499998
il valore medio per il percentile21.56 è: 9855.1314
il valore medio per il percentile28.12 è: 14394.936549999999
il valore medio per il percentile40.565 è: 33541.58601666667
il valore medio per il percentile27.645 è: 13066.559164285716
il valore medio per il percentile31.2 è: 9625.92
il valore medio per il percentile26.62 è: 5749.9773000000005
il valore medio per il percentile48.07 è: 9432.9253
il valore medio per il percentile36.765 è: 29448.57969
il valore medio per il percentile33.4 è: 17461.14311
il valore medio per il percentile45.54 è: 42112.2356
il valore medio per il percentile28.82 è: 2156.7518
il valore medio per il percentile22.99 è: 15368.082766666668
il valore medio per il percentile27.7 è: 8755.409
il valore medio per il percentile25.41 è: 21978.6769
il valore medio per il percentile34.39 è: 25245.1446
il valore medio per il percentile22.61 è: 9811.41565
il valore medio per il percentile37.51 è: 10785.1044
il valore medio per il percentile38.0 è: 10069.535666666665
il valore medio per il percentile33.33 è: 14032.503765714288
il valore medio per il percentile34.865 è: 7422.04185
il valore medio per il percentile33.06 è: 7749.1564
il valore medio per il percentile35.97 è: 18246.2133
il valore medio per il percentile31.4 è: 24221.497333333333
il valore medio per il percentile25.27 è: 9903.4363
il valore medio per il percentile40.945 è: 11566.30055
il valore medio per il percentile34.105 è: 23987.6007
il valore medio per il percentile36.48 è: 22597.85034
il valore medio per il percentile33.8 è: 47928.03
il valore medio per il percentile36.7 è: 9144.565
il valore medio per il percentile36.385 è: 29977.15065
il valore medio per il percentile34.5 è: 13822.803
il valore medio per il percentile32.3 è: 14100.05772
il valore medio per il percentile27.6 è: 14942.895108000002
il valore medio per il percentile29.26 è: 5357.730149999999
il valore medio per il percentile35.75 è: 27815.46483333333
il valore medio per il percentile23.18 è: 9868.629729999999
il valore medio per il percentile25.6 è: 13233.9825
il valore medio per il percentile35.245 è: 11899.472324999999
il valore medio per il percentile43.89 è: 27572.5501
il valore medio per il percentile20.79 è: 1607.5101
il valore medio per il percentile30.5 è: 7646.939249999999
il valore medio per il percentile21.7 è: 13844.506
il valore medio per il percentile21.89 è: 3180.5101
il valore medio per il percentile24.985 è: 15629.26784
il valore medio per il percentile32.015 è: 26913.23835
il valore medio per il percentile30.4 è: 12038.483079999998
il valore medio per il percentile21.09 è: 13415.0381
il valore medio per il percentile22.23 è: 7602.787200000001
il valore medio per il percentile32.9 è: 14403.010333333332
il valore medio per il percentile24.89 è: 21659.9301
il valore medio per il percentile31.46 è: 14439.457065
il valore medio per il percentile17.955 è: 15006.57945
il valore medio per il percentile30.685 è: 28030.11615
il valore medio per il percentile43.34 è: 5846.9176
il valore medio per il percentile39.05 è: 22957.9895
il valore medio per il percentile30.21 è: 16582.65495
il valore medio per il percentile31.445 è: 11469.25805
il valore medio per il percentile19.855 è: 6492.37645
il valore medio per il percentile31.02 è: 19455.80277
il valore medio per il percentile38.17 è: 15428.876966666669
il valore medio per il percentile20.6 è: 5498.237
il valore medio per il percentile47.52 è: 8083.9198
il valore medio per il percentile20.4 è: 3260.199
il valore medio per il percentile38.38 è: 12173.485700000001
il valore medio per il percentile24.31 è: 6986.981900000001
il valore medio per il percentile23.6 è: 6735.659
il valore medio per il percentile21.12 è: 6652.5288
il valore medio per il percentile30.03 è: 5057.570699999999
il valore medio per il percentile17.48 è: 1621.3402
il valore medio per il percentile20.235 è: 7722.5619
il valore medio per il percentile17.195 è: 14455.64405
il valore medio per il percentile23.9 è: 5080.096
il valore medio per il percentile35.15 è: 2134.9015
il valore medio per il percentile35.64 è: 7345.7266
il valore medio per il percentile22.6 è: 10532.882
il valore medio per il percentile39.16 è: 9840.709733333335
il valore medio per il percentile27.265 è: 10789.316672500001
il valore medio per il percentile29.165 è: 7323.734818999999
il valore medio per il percentile16.815 è: 4904.00035
il valore medio per il percentile33.1 è: 13917.484082500001
il valore medio per il percentile26.9 è: 5969.723000000001
il valore medio per il percentile33.11 è: 23126.36465
il valore medio per il percentile31.73 è: 16973.5177
il valore medio per il percentile46.75 è: 12592.5345
il valore medio per il percentile29.45 è: 2897.3235
il valore medio per il percentile32.68 è: 13881.48728
il valore medio per il percentile33.5 è: 37079.372
il valore medio per il percentile43.01 è: 1149.3959
il valore medio per il percentile36.52 è: 28287.89766
il valore medio per il percentile26.695 è: 15608.553049999999
il valore medio per il percentile25.65 è: 11454.0215
il valore medio per il percentile29.6 è: 9132.684315
il valore medio per il percentile38.6 è: 7543.7675
il valore medio per il percentile23.4 è: 2441.5915000000005
il valore medio per il percentile46.53 è: 4683.025699999999
il valore medio per il percentile30.14 è: 6506.7381000000005
il valore medio per il percentile30.0 è: 12524.060000000001
il valore medio per il percentile38.095 è: 32905.48159666667
il valore medio per il percentile28.38 è: 19521.9682
il valore medio per il percentile28.7 è: 8533.0666
il valore medio per il percentile33.82 è: 10539.2232825
il valore medio per il percentile24.09 è: 2201.0971
il valore medio per il percentile32.67 è: 6652.2623
il valore medio per il percentile25.1 è: 25382.297
il valore medio per il percentile32.56 è: 21382.7854
il valore medio per il percentile41.325 è: 13694.954393333333
il valore medio per il percentile39.5 è: 5781.3324999999995
il valore medio per il percentile34.3 è: 9563.029
il valore medio per il percentile31.065 è: 11681.417100000002
il valore medio per il percentile21.47 è: 5843.758966666667
il valore medio per il percentile25.08 è: 10740.976412
il valore medio per il percentile43.4 è: 12574.049
il valore medio per il percentile25.7 è: 13521.952000000001
il valore medio per il percentile27.93 è: 8989.60594
il valore medio per il percentile39.2 è: 13470.86
il valore medio per il percentile26.03 è: 6439.5603
il valore medio per il percentile30.25 è: 18126.3475
il valore medio per il percentile28.93 è: 9889.001366666665
il valore medio per il percentile35.7 è: 11362.755
il valore medio per il percentile35.31 è: 23265.217109999998
il valore medio per il percentile31.0 è: 5364.5135
il valore medio per il percentile44.22 è: 4130.1718
il valore medio per il percentile26.07 è: 38245.59327
il valore medio per il percentile25.8 è: 5665.668428571429
il valore medio per il percentile39.425 è: 8342.90875
il valore medio per il percentile40.48 è: 13831.1152
il valore medio per il percentile38.9 è: 5972.378000000001
il valore medio per il percentile47.41 è: 63770.42801
il valore medio per il percentile35.435 è: 3268.84665
il valore medio per il percentile46.7 è: 11538.421
il valore medio per il percentile46.2 è: 45863.205
il valore medio per il percentile21.4 è: 11511.265500000001
il valore medio per il percentile23.8 è: 3847.674
il valore medio per il percentile44.77 è: 9058.7303
il valore medio per il percentile32.12 è: 2801.2588
il valore medio per il percentile29.1 è: 3761.292
il valore medio per il percentile37.29 è: 4099.29785
il valore medio per il percentile43.12 è: 4753.6368
il valore medio per il percentile36.86 è: 26732.92062
il valore medio per il percentile34.295 è: 13224.05705
il valore medio per il percentile23.465 è: 4804.39135
il valore medio per il percentile45.43 è: 6356.2707
il valore medio per il percentile23.65 è: 17626.23951
il valore medio per il percentile20.7 è: 1242.816
il valore medio per il percentile28.27 è: 5132.034799999999
il valore medio per il percentile35.91 è: 20013.949095

In [248]:
df=pd.read_csv(r"C:\Users\pagod\OneDrive\Desktop\Python\beginner_datasets\pokemon.csv")

In [250]:
df.size

10400

In [252]:
df.shape

(800, 13)

In [266]:
df.columns

Index(['#', 'Name', 'Type 1', 'Type 2', 'Total', 'HP', 'Attack', 'Defense',
       'Sp. Atk', 'Sp. Def', 'Speed', 'Generation', 'Legendary'],
      dtype='object')

In [272]:
df["#"].value_counts()

#
479    6
386    4
710    4
711    4
646    3
      ..
250    1
251    1
252    1
253    1
721    1
Name: count, Length: 721, dtype: int64

In [274]:
df.set_index("#")

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
#,,,,,,,,,,,,
1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [280]:
filtro=df["Legendary"]==True
Leggendari=df.loc[filtro,"Name"]
Leggendari_unici=Leggendari.unique()
print(Leggendari_unici)

['Articuno' 'Zapdos' 'Moltres' 'Mewtwo' 'MewtwoMega Mewtwo X'
 'MewtwoMega Mewtwo Y' 'Raikou' 'Entei' 'Suicune' 'Lugia' 'Ho-oh'
 'Regirock' 'Regice' 'Registeel' 'Latias' 'LatiasMega Latias' 'Latios'
 'LatiosMega Latios' 'Kyogre' 'KyogrePrimal Kyogre' 'Groudon'
 'GroudonPrimal Groudon' 'Rayquaza' 'RayquazaMega Rayquaza' 'Jirachi'
 'DeoxysNormal Forme' 'DeoxysAttack Forme' 'DeoxysDefense Forme'
 'DeoxysSpeed Forme' 'Uxie' 'Mesprit' 'Azelf' 'Dialga' 'Palkia' 'Heatran'
 'Regigigas' 'GiratinaAltered Forme' 'GiratinaOrigin Forme' 'Darkrai'
 'ShayminLand Forme' 'ShayminSky Forme' 'Arceus' 'Victini' 'Cobalion'
 'Terrakion' 'Virizion' 'TornadusIncarnate Forme' 'TornadusTherian Forme'
 'ThundurusIncarnate Forme' 'ThundurusTherian Forme' 'Reshiram' 'Zekrom'
 'LandorusIncarnate Forme' 'LandorusTherian Forme' 'Kyurem'
 'KyuremBlack Kyurem' 'KyuremWhite Kyurem' 'Xerneas' 'Yveltal'
 'Zygarde50% Forme' 'Diancie' 'DiancieMega Diancie' 'HoopaHoopa Confined'
 'HoopaHoopa Unbound' 'Volcanion']

In [284]:
Filtro2=(df["Legendary"]==True) & (df["Type 1"]=="Grass")
Leggendari2=df.loc[Filtro2,"Name"]
Leggendari_unici2=Leggendari2.unique()
print(Leggendari_unici2)

['ShayminLand Forme' 'ShayminSky Forme' 'Virizion']

In [292]:
Filtro3=(df["Legendary"]==True) & ((df["Type 1"]=="Fire") | (df["Type 1"]=="Ice"))
Leggendari3=df.loc[Filtro3,"Name"]
Leggendari_unici3=Leggendari3.unique()
print(Leggendari_unici3)

['Articuno' 'Moltres' 'Entei' 'Ho-oh' 'Regice' 'Heatran' 'Volcanion']

In [296]:
tab_ordinata=df.sort_values(by="Name", ascending=True)
print(tab_ordinata)

       #                     Name   Type 1  Type 2  Total   HP  Attack  \
510  460                Abomasnow    Grass     Ice    494   90      92
511  460  AbomasnowMega Abomasnow    Grass     Ice    594   90     132
68    63                     Abra  Psychic     NaN    310   25      20
392  359                    Absol     Dark     NaN    465   65     130
393  359          AbsolMega Absol     Dark     NaN    565   65     150
..   ...                      ...      ...     ...    ...  ...     ...
632  571                  Zoroark     Dark     NaN    510   60     105
631  570                    Zorua     Dark     NaN    330   40      65
46    41                    Zubat   Poison  Flying    245   40      45
695  634                 Zweilous     Dark  Dragon    420   72      85
794  718         Zygarde50% Forme   Dragon  Ground    600  108     100

     Defense  Sp. Atk  Sp. Def  Speed  Generation  Legendary
510       75       92       85     60           4      False
511      105      132      105     30           4      False
68        15      105       55     90           1      False
392       60       75       60     75           3      False
393       60      115       60    115           3      False
..       ...      ...      ...    ...         ...        ...
632       60      120       60    105           5      False
631       40       80       40     65           5      False
46        35       30       40     55           1      False
695       70       65       70     58           5      False
794      121       81       95     95           6       True

[800 rows x 13 columns]

In [298]:
Filtro5=(df["HP"]<60) & (df["Attack"]>50)  & (df["Generation"]==1)
Leggendari5=df.loc[Filtro5,"Name"]
Leggendari_unici5=Leggendari5.unique()
print(Leggendari_unici5)

['Charmander' 'Charmeleon' 'Wartortle' 'Rattata' 'Raticate' 'Spearow'
 'Ekans' 'Pikachu' 'Sandshrew' 'Nidoran♂' 'Paras' 'Diglett' 'Dugtrio'
 'Psyduck' 'Mankey' 'Growlithe' 'Bellsprout' 'Geodude' 'Graveler' 'Ponyta'
 'Magneton' "Farfetch'd" 'Doduo' 'Shellder' 'Cloyster' 'Krabby' 'Kingler'
 'Hitmonlee' 'Hitmonchan' 'Koffing' 'Seadra' 'Goldeen' 'Eevee' 'Kabuto'
 'Dratini']